import React from 'react';
import ReactDOM from 'react-dom';
import 'bootstrap/dist/css/bootstrap.min.css';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

localStorage.setItem('token', 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImY2MFJ6U3lQN21iRERIWlA4QVE2NzVxems4MENkM2hEa21OWHR3XzA0a2cifQ.eyJleHAiOjE1NzA1MzA4MDQsIm5iZiI6MTU3MDUyNzIwNCwidmVyIjoiMS4wIiwiaXNzIjoiaHR0cHM6Ly9nb29yZy5iMmNsb2dpbi5jb20vNmQ5Y2FkMmYtN2UwYy00NWY2LThlNWQtNDI5NGE5ODZiZGIwL3YyLjAvIiwic3ViIjoiOGY3YWM0YjItM2UzNS00ZjBhLThiOTAtY2Q0MzMxNmNmY2JmIiwiYXVkIjoiZTZhMTA1NTUtOThhZC00ZDFjLThhYzEtYzJiZmI0OTczYWE5IiwiYWNyIjoiYjJjXzFhX3NpZ251cF9zaWduaW4iLCJub25jZSI6ImYwMjVmYmU4LTcxYTctNDZhYi1hNTU1LWU0NmZlYzcyNDM4MCIsImlhdCI6MTU3MDUyNzIwNCwiYXV0aF90aW1lIjoxNTcwNTI3MjA0LCJvaWQiOiI4ZjdhYzRiMi0zZTM1LTRmMGEtOGI5MC1jZDQzMzE2Y2ZjYmYiLCJuYW1lIjoiR2V2ZW5kcmEgU2FodSIsImVtYWlscyI6WyJnZXZlbmRyYUBieW9tLmRlIl0sImdpdmVuX25hbWUiOiJHZXZlbmRyYSIsImZhbWlseV9uYW1lIjoiU2FodSIsInJvbGVzIjpbIkhpdmVBZG1pbiJdLCJpc0FjdGl2ZSI6dHJ1ZSwiaXNBcHByb3ZlZCI6dHJ1ZSwicmVnaXN0cmF0aW9uRGF0ZVRpbWUiOiIxMC8zLzIwMTkgMTI6NDg6NDEgUE0ifQ.2Q8wgFf9h74tu_1mFMmLQt-cG1Hssa_knBURFJu-jAM5Gfvvm8jPZYrp5_c2R5O4EPyD2boRVzpwCKbGmzCqckZ6ReRcGmC2J0IRMEUTs_F-Ey8IBuc2rb7bNCpzKNEPm4fXwVofp3djcVomIUIZ9mWCmfpOzhf0tvlWwlcTWXiyzhdoQvIi51CCKm6G0DAZ6GCqjAPBwCOn6Y6dT8qrPZefOk3J-WpsijiK50dbsHuUctWkxdXyBYKmNNs5TNXFxF7PG9Xj82iJjcPsiuR5wZanGvzijzZxypNXR88cpXusmFeT7qvV6RoWWBbLZhKvpx1UtDN1hk_Z_pN0Nq7ELw');
ReactDOM.render(<App />, document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
